name = "convex-svelte-demo"
main = "./.svelte-kit/cloudflare/_worker.js"
assets = { directory = "./.svelte-kit/cloudflare", binding = "ASSETS" }
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "cf535d76fffdb44d43f6a3c00a3ebbe6"

[build]
command = "npm run build"

# Environment variables for production
[env.production.vars]
# Add your production Convex configuration here
# CONVEX_SELF_HOSTED_URL = "https://your-production-convex-server.com"
# PUBLIC_CONVEX_URL = "https://your-production-convex-server.com"

# Environment variables for staging
[env.staging.vars]
# Add your staging Convex configuration here
# CONVEX_SELF_HOSTED_URL = "https://your-staging-convex-server.com"
# PUBLIC_CONVEX_URL = "https://your-staging-convex-server.com"

# Secrets (use wrangler secret put command to set these)
# CONVEX_SELF_HOSTED_ADMIN_KEY
# CONVEX_DEPLOY_KEY
